# metamodel_version: 1.7.0
enum HabitatEnum
  {
    Cave
    Forest
    Grassland
  }

type Ability
  {
    id: String!
    name: String
    description: String
    effectDescription: [String]
  }

type BattleItem
  {
    id: String!
    name: String
    description: String
  }

type Berry
  {
    id: String!
    name: String
    description: String
    hasFlavor: [Flavor]
    firmness: Int
    smoothness: Int
    hasSize: String
  }

type Colour
  {
    id: String!
    name: String
    description: String
    black: Float
    cyanic: Float
    magenta: Float
    yellow: Float
    hue: Float
    saturation: Float
    value: Float
    red: Int
    green: Int
    blue: Int
    wavelength: Float
  }

type EggGroup
  {
    id: String!
    description: String
    name: String!
  }

type Flavor
  {
    id: String!
    description: String
    name: String!
  }

type Food
  {
    id: String!
    name: String
    description: String
    hasFlavor: [Flavor]
    firmness: Int
    smoothness: Int
  }

type Game
  {
    id: String!
    name: String
    description: String
  }

type Generation
  {
    id: String!
    name: String
    description: String
    featuresSpecies: [Species]
  }

type Gym
  {
    id: String!
    name: String
    description: String
  }

type GymLeader
  {
    id: String!
    description: String
    name: String!
    depiction: String
  }

type Habitat
  {
    id: String!
    description: String
    name: String!
  }

type HM
  {
    id: String!
    name: String
    description: String
  }

type HoldItem
  {
    id: String!
    name: String
    description: String
  }

type Item
  {
    id: String!
    name: String
    description: String
  }

type LearningByLevelingUp
  {
  }

type LearningThroughBreeding
  {
  }

type Medicine
  {
    id: String!
    name: String
    description: String
  }

type Move
  {
    id: String!
    name: String
    description: String
    effectDescription: [String]
    hasType: [Type]
  }

type MoveLearning
  {
  }

interface NamedIndividual
  {
    id: String!
    description: String
    name: String!
  }

type Person
  {
    id: String!
    description: String
    name: String!
    depiction: String
  }

type PhysicalMove
  {
    id: String!
    name: String
    description: String
    effectDescription: [String]
    hasType: [Type]
  }

interface Place
  {
    id: String!
    name: String
    description: String
  }

type Pokeball
  {
    id: String!
    name: String
    description: String
  }

type Pokedex
  {
    id: String!
    name: String
    description: String
  }

type PokedexEntry
  {
    id: String!
    name: String
    description: String
  }

type Pokemon
  {
  }

type Quantity
  {
    id: String!
    name: String
    description: String
    hasUnit: [Unit]
    hasQuantityKind: QuantityKind
    hasValue: String
  }

type QuantityKind
  {
  }

type Region
  {
    id: String!
    name: String
    description: String
  }

type Shape
  {
    id: String!
    description: String
    name: String!
  }

type SpecialMove
  {
    id: String!
    name: String
    description: String
    effectDescription: [String]
    hasType: [Type]
  }

type Species
  {
    id: String!
    description: String
    name: String!
    hasColour: Colour
    mayHaveHiddenAbility: [Ability]
    mayHaveAbility: [Ability]
    isAbleToApply: [Move]
    hasHeight: Quantity
    hasWeight: Quantity
    depiction: String
    inEggGroup: [EggGroup]
    hasType: [Type]
    hasShape: Shape
    hasGenus: String
    hasCatchRate: Int
    foundIn: [Habitat]
  }

type StatusMove
  {
    id: String!
    name: String
    description: String
    effectDescription: [String]
    hasType: [Type]
  }

interface Thing
  {
    id: String!
    name: String
    description: String
  }

type TM implements MoveLearning
  {
    id: String!
    name: String
    description: String
  }

type Town
  {
    id: String!
    name: String
    description: String
  }

type Trainer
  {
    id: String!
    description: String
    name: String!
    depiction: String
  }

type Type
  {
    id: String!
    description: String
    name: String!
  }

type Unit
  {
    id: String!
    name: String
    description: String
  }
