# metamodel_version: 1.7.0
type Ability
  {
    name: String
    description: String
    id: Uri!
    effectDescription: [String]
  }

type BattleItem
  {
  }

type Berry
  {
    hasSize: String
  }

type Colour
  {
  }

type EggGroup
  {
  }

type Entity
  {
    name: String
    description: String
    id: Uri!
  }

type Flavor
  {
  }

type Food
  {
  }

type Game
  {
  }

type Generation
  {
    featuresSpecies: [Species]
  }

type Gym
  {
  }

type GymLeader
  {
  }

type Habitat
  {
  }

type HM
  {
  }

type HoldItem
  {
  }

type Item
  {
  }

type LearningByLevelingUp
  {
  }

type LearningThroughBreeding
  {
  }

type Medicine
  {
  }

type Move
  {
    name: String
    description: String
    id: Uri!
    effectDescription: [String]
    hasType: [Type]
  }

type MoveLearning
  {
  }

type NamedThing
  {
    id: Uri!
    name: String
    description: String
  }

type PhysicalMove
  {
    name: String
    description: String
    id: Uri!
    effectDescription: [String]
    hasType: [Type]
  }

type Place
  {
  }

type Pokeball
  {
  }

type Pokedex
  {
  }

type PokedexEntry
  {
  }

type Pokemon
  {
  }

type Region
  {
  }

type Shape
  {
  }

type SpecialMove
  {
    name: String
    description: String
    id: Uri!
    effectDescription: [String]
    hasType: [Type]
  }

type Species
  {
    id: Uri!
    name: String
    description: String
    hasColour: [Colour]
    mayHaveHiddenAbility: [Ability]
    mayHaveAbility: [Ability]
    isAbleToApply: [Move]
    hasHeight: String
    hasWeight: String
    depiction: String
    inEggGroup: [EggGroup]
    hasType: [Type]
    hasShape: Shape
    hasGenus: String
    hasCatchRate: Integer
    foundIn: [Habitat]
  }

type StatusMove
  {
    name: String
    description: String
    id: Uri!
    effectDescription: [String]
    hasType: [Type]
  }

type Thing
  {
    id: Uri!
  }

type TM
  {
  }

type Town
  {
  }

type Trainer
  {
  }

type Type
  {
  }

