 syntax="proto3";
 package
// metamodel_version: 1.7.0
message Ability
 {
  string name = 0
  string description = 0
  uri id = 0
 repeated  string effectDescription = 0
 }
message Berry
 {
  string hasSize = 0
 }
// A grouping of attributes that can be reffered to
message Entity
 {
  string name = 0
  string description = 0
  uri id = 0
 }
message Generation
 {
 repeated  species featuresSpecies = 0
 }
message Move
 {
  string name = 0
  string description = 0
  uri id = 0
 repeated  string effectDescription = 0
 repeated  type hasType = 0
 }
// A generic grouping for any identifiable entity that has a name
message NamedThing
 {
  uri id = 0
  string name = 0
  string description = 0
 }
// A physical move is a type of move that can be used during battles.
message PhysicalMove
 {
  string name = 0
  string description = 0
  uri id = 0
 repeated  string effectDescription = 0
 repeated  type hasType = 0
 }
// A special move is a type of move that can be used during battles.
message SpecialMove
 {
  string name = 0
  string description = 0
  uri id = 0
 repeated  string effectDescription = 0
 repeated  type hasType = 0
 }
// A species is a category of Pokemon that share common features.
message Species
 {
  uri id = 0
  string name = 0
  string description = 0
 repeated  colour hasColour = 0
 repeated  ability mayHaveHiddenAbility = 0
 repeated  ability mayHaveAbility = 0
 repeated  move isAbleToApply = 0
  string hasHeight = 0
  string hasWeight = 0
  string depiction = 0
 repeated  eggGroup inEggGroup = 0
 repeated  type hasType = 0
  shape hasShape = 0
  string hasGenus = 0
  integer hasCatchRate = 0
 repeated  habitat foundIn = 0
 }
// A status move is a type of move that can be used during battles.
message StatusMove
 {
  string name = 0
  string description = 0
  uri id = 0
 repeated  string effectDescription = 0
 repeated  type hasType = 0
 }
// A generic grouping for any identifiable attributes with an id
message Thing
 {
  uri id = 0
 }

