---
name: Auto-deployment of linkml_pokemon Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # allow to generate an OpenID Connect (OIDC) token

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # otherwise, you will fail to push refs to dest repo


      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13

      - name: Install just
        run: |
          uv tool install rust-just

      - name: Install dependencies
        run: uv sync --dev --no-progress

      - name: Generate schema documentation
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          make mkd-gh-deploy
